#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service
SERVICE_NAME="ncwbcs"

check_container_initialized

transform_var file \
                    JWT_SECRET_KEY \
                    NEXTCLOUD_URL

export BACKUP_DIR=${BACKUP_PATH}
export NODE_ENV=production
export NEXTCLOUD_URL=${NEXTCLOUD_URL}
export JWT_SECRET_KEY=${JWT_SECRET_KEY}

cd /app
liftoff

print_start "Starting Nextcloud Whiteboard Collaboration Server $(grep -o "ADD: Nextcloud Whiteboard .* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $4}')"
exec s6-setuidgid ncwbcs \
                            npm \
                                run \
                                    server:start
